### ISSUE TITLE
It should generate <= 10 emojis but 14 generated

### ISSUE THREAD

**Issue by legend80s** [aleksdotbar/emojisearch.fun#1]
It should generate <= 10 emojis but 14 generated

![image](https://github.com/user-attachments/assets/03b5e691-2da3-4db2-89aa-008d5f399a0b)

**Comment by legend80s** [comment]
May be the prompt should be more specific or the we can use `slice` to limit the ChatGPT output.

**Comment by legend80s** [comment]
I am not good at writing prompt so I just add this issue.

**Comment by aleksdotbar** [comment]
There is no requirement for <= 10 emojis
